---
title: "Summit County COVID-19 Dashboard. Last updated 2020-07-18."
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(rmarkdown)
library(plotly)

covid <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")

summit <- covid %>% filter(county=="Summit" & state=="Colorado")
summit$new_cases <- c(NA, diff(summit$cases, lag = 1))
last_30_summit <- tail(summit, 30)
last_30_summit$new_cases <- c(NA, diff(last_30_summit$cases, lag=1))
```

Plots
=====================================
Column {.sidebar}
-----------------------------------------------------------------------
Some notes about this data...

- __This dashboard is not intended to provide medical advice!__  If you have questions about your symptoms, please consult with a physician.

- __This dashboard is not intended to provide conclusions!__  If you want to draw conclusions on what you see here, that is up to you.

- __There are sometimes negative numbers in the number of cases!__  This could be from a variety of reasons, including a case being removed from Summit County and assigned to a different county or even just a typo.  This dashboard presents the raw data and, without additional information, I am not correcting it in any way.

- __There are sometimes no new cases!__  These show up as missing bars on the plot of the new cases for the last 30 days. While this frequently correlates with the weekends (see below), it also shows that there were no new positive tests for that day.  There are also occasional updates by the NY Times to the database, which can result in a few days data not being immediately updated.

- The data herein have been obtained from the [New York Times Dataset](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv), which is updated daily and available for free download.  This data is not impacted by the recent move from the CDC collection to the White House because the CDC data is specifically on hospitalization whereas this data is only on testing.  So it is not impacted by this move.

- The blue lines represent a mathematical fit to the existing data. The grey shaded sections are the calculated uncertainty in that fit.

- The data might not be updated over the weekend, or the counts might be artificially low due to less staff at the labs over the weekends.

- I am maintaining this dashboard on my own and through no assistance or funding. It is open source and anyone is free to download it [here](https://github.com/cj2001/summit_county_covid).  Note that I have yet to add in automated updating, so this is still a manual process.

- For any questions about this dashboard, please contact @cjisalock on Twitter (keep it respectful or you will be blocked!).

Column 
-----------------------------------------------------------------------

### Total Year to Date Cases

```{r}
ggplotly(
  ggplot(data = summit, aes(x=date, y=cases)) +
    stat_smooth(method="lm", formula = y ~ poly(x, 5), size=1) + 
    geom_point() +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
)
```


### Total Cases for the Last 30 Days

```{r}
ggplotly(
  ggplot(data = last_30_summit) + 
    geom_point(mapping = aes(x=date, y=cases)) + 
    geom_smooth(mapping = aes(x=date, y=cases)) +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
)
```

Column 
-----------------------------------------------------------------------

### New Cases per Day

```{r}
ggplotly(
  ggplot(data = summit) + 
    geom_point(mapping = aes(x=date, y=new_cases)) + 
    geom_smooth(mapping = aes(x=date, y=new_cases)) +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
)
```

### New Cases in the Last 30 Days

```{r}
type <- c(last_30_summit$cases)
ggplotly(
  ggplot(data = last_30_summit, aes(x=date, y=new_cases)) +
    geom_bar(stat="identity", aes(fill = type), show.legend = FALSE) +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
)
```

Raw Data
=====================================
Column 
-----------------------------------------------------------------------
### Raw Data

```{r}
summit$date <- format(summit$date) # Puts dates in YYYY-MM-DD format for table
renderTable({
  summit
})
```